wonday/react-native-pdf

react-native-pdf.podspec

LMK if it looks good and I'll update the README as well.

Added podspec

---

android/src/main/java/org/wonday/pdf/PdfView.java

This PR brings support to Android for others schemes like `content://` in addition to `file://`.

feat: Android uri support

---

README.md
issue_template.md

Update readme and issue template added

Update readme and issue template added 

---

index.js

Fix pdfs when pipe appears in json

---

README.md

I added the table for the compatibility though you will certainly have to update it to specify more or less cause I don't know all the compatibility ;)

 Add version compatibility section

---

index.js.flow

To work, requires `rn-fetch-blob` 0.10.15, so perhaps update recommendations in the readme?
See: https://flow.org

Add flow typings

---

DoubleTapView.js
PdfView.js
index.js

Fixed all `componentWillReceiveProps` and `componentWillMount` warnings
#382

PR to fix react-native warning on `componentWill*`

---

index.js

Avoids errors when opening PDF then closing mid-load.

Fix calling setState while unmounted

---

index.js.flow

Use ViewStyleProp in index.js.flow, not deprecated StyleSheet.Styles

---

ios/RCTPdf/RCTPdfView.m

run handleDoubleTap explicitly in the main thread, animate changing the scale factor and go to the tapped area

Issue #450 - iOS Double Tap zoom

---

index.js

Issue existed for a very long time
https://github.com/wonday/react-native-pdf/issues/354#issuecomment-509514188

ReferenceError; url should be source.uri

---

PdfView.js
README.md
android/src/main/java/org/wonday/pdf/PdfView.java
android/src/main/java/org/wonday/pdf/RCTPdfManager.java
index.d.ts
index.js
index.js.flow
ios/RCTPdf/RCTPdfView.h
ios/RCTPdf/RCTPdfView.m
ios/RCTPdf/RCTPdfViewManager.m

Provides a new `singlePage` property that only displays first (or current) page and disables all interactions. This makes it suitable for a thumbnail or cover page.

singlePage property

---

ios/RCTPdf/RCTPdfView.m

… `reactSetFrame` may be called, then setDocument `_pdfView.document = _pdfDocument;` will end editing the `TextInput` and the keyboard be hidden. Cannot input anything on blur.

fix bug: iOS, TextInput cannot input, the keyboard will be hidden and the TextInput be blurred.

---

index.js

Fixed blank screen when space occurs in filename

---

windows/RCTPdf/pch.h

This fixed the #683 for me. 
Are there any additional Task I need to do? Let me know!

Fix Issue 683 | Windows Build fail

---

PdfView.js

Updated PdfView.js

---

android/build.gradle
android/src/main/AndroidManifest.xml

https://github.com/react-native-community/discussions-and-proposals/issues/671

fix: RN 73 compatibility

---

index.d.ts

I create a PR last time as well, forgot to add export there

export PDF Props (Updated index.d.ts)

---

README.md
package.json

Version 6.7.4
Hey, could you please release a new version with the latest fixes? 🙏
I've added boilerplate changes for release in this PR

Version bump to 6.7.4

---

ios/RNPDFPdf/RNPDFPdfView.mm

We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)
or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)
---
PR adding `load` method needed …

feat: add load method

---

fabric/RNPDFPdfNativeComponent.js
ios/RNPDFPdf/RNPDFPdfView.mm

[#878](https://github.com/wonday/react-native-pdf/issues/878) fixed

:bug: enableDoubleTapZoom bugfix

---

android/build.gradle

Just upgrades the pdfium library. This fixes issue #864

fix: fix field values not being visible on android. issue #864 :bug:

---

ios/RNPDFPdf/RNPDFPdfView.mm

As suggested on #913, #839, #841#issuecomment-2694404261 and https://github.com/wonday/react-native-pdf/commit/bcaff69ed3a1ca07378f5c06e3682626cfa13b0c#r142281526
Fixes #839
Fixes #841
Fixes #913

Fix clicking links on ios
