wonday/react-native-pdf

ios/RCTPdf.xcodeproj/project.pbxproj
ios/RCTPdf/RCTPdfView.h
ios/RCTPdf/RCTPdfView.m
ios/RCTPdf/RCTPdfViewManager.h
ios/RCTPdf/RCTPdfViewManager.m
ios/RCTPdf/WPdfView.h
ios/RCTPdf/WPdfView.m

To fix this and maintain backwards compatibility with RN <= 0.39 without having to branch you can also change your includes like below, using #if __has_include. That's what we did for our React Native libraries and it worked well.
```
// Support React Native headers both in the React namespace, where they are in RN version 0.40+,
// and no namespace, for older versions of React Native
#if __has_include(<React/RCTBridge.h>)
#import <React/RCTBridge.h>
#else
#import "RCTBridge.h"
#endif
```
from [react-native-fetch-blob/issues/244](https://github.com/wkh237/react-native-fetch-blob/issues/244)

Support React Native headers both in the React namespace

---

index.d.ts

`onLoadComplete` callback takes `pageCount` as parameter. 
`onPageChanged` callback takes `page` and `pageCount` as parameters.

Fix for TypeScript definitions (onLoadComplete and onPageChanged)

---

index.js
package-lock.json
package.json

PropTypes was removed react in v15.5 and moved into it's own package. https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes
This PR implements that change so the warning no longer shows while developing. 
If you're wondering, the package-lock is a new standard which released in npm5 which makes installs much faster.
Also formatted the code a bit :P

Replace PropTypes with prop-types package

---

android/src/main/java/org/wonday/pdf/RCTPdfView.java

This PR makes this package compatible with RN 0.47.0 (see [this commit](https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8)).

Remove deprecated android override for RN 0.47.0 compatibility

---

index.d.ts

The callback `onError` takes one parameter of type `string` (see README example code).

Fix TypeScript definition for onError

---

index.js

Rolled this up real quick. Any feedback? :)
My use case is to use the pdf file path for the iOS Share dialogue.

Add loaded pdf path on onLoadComplete callback

---

android/build.gradle

Incerease of android-pdf-viewer version to 2.8.1 to fix similar bug we faced with during development: https://github.com/barteksc/AndroidPdfViewer/issues/25

increase android-pdf-viewer version to 2.8.1

---

index.js

Hello and thanks for great library!
When remote server responds with non-200 status code promise from `react-native-fetch-blob` is not rejected. This PR implements basic status code handling.

HTTP status code handling

---

README.md

Trying to install react-native-pdf as shown in the guide was throwing an UNMET_PEER_DEPENDENCY error.
The solution is simple, it will just work installing react-native-fetch-blob before react-native-pdf
I have just changed it on the README.md

Readme hotfix: Changed the installation order at the guide

---

index.js

Solved this problem: 
`When running, it shows 'Pdf' has no propType for native prop RCTPdf.acessibilityLabel of native type 'String'`.
Add missing props to prevent crash on earlier react native version, there's no need to update to react-native@0.47 but still need to have FlatList

[Android] Crashed because of missing props

---

PdfPageView.js
PdfView.js

PdfPageView act as item component in FlatList and it rendered too many times, like when you scroll, zoom, etc ...
Turn it into PureComponent to remove wasted render.

Using pure component to render pdf pages

---

ios/RCTPdf/PdfManager.m

RN 0.52 warning that, because PDFManager overrides 'init', it requires main queue setup, but does not implement 'requiresMainQueueSetup.' This PR implements 'requiresMainQueueSetup' and fixes the warning.

Add requiresMainQueueSetup to cure RN v0.52 warning

---

index.js

It is used for POST requests that need a body parameter to load data from a server.

Use 'body' parameter of source if exists

---

index.js

Handle promise rejection when cached file already exists after a succesful fetch.
Pass the error object to the onError handler.

Fix unhandled promise rejection when cached file already exists

---

index.js

Hi!
It's better to let the consumer decides whether or not an error should be log.
I also normalized the error handle so that only error objects will be passed.
Changes:
- Remove console.(log|warn|error) 
- Always pass errors to the error handler.

Remove logs & pass errors to the onError handler

---

DoubleTapView.js

Scrolling the PDF would cause onSingleTap to get called.
This PR does not consider a gesture a tap if the user's finger has moved too far. I chose 10 arbitrarily, it seemed to feel pretty natural when testing. This allows a user to scroll the PDF document without triggering the onSingleTap event handler.

Do not count a scrolling gesture as a tap

---

react-native-pdf.podspec

Add React dependency to podspec to support CocoaPods 1.5.0
CocoaPods 1.5.0 does no longer add all header search paths for each xcconfig generated and instead, it only adds the header search paths for the dependencies of the pod as stated in http://blog.cocoapods.org/CocoaPods-1.5.0/
As a result, implicit dependencies are no longer working.

Add React dependency to podspec

---

index.js

The condition on the expiration is wrong, it doesn't work as described in the documentation.
given a source.expiration = undefined
!!!source.expiration -> true
Boolean(source.expiration) -> false

fixed condition on cache expiration

---

PdfView.js
README.md

Include the document dimensions as a new third parameter to the `onLoadComplete` callback.
This information can be used by a parent component to resize itself to ensure that a complete page is shown when the document size could vary.

Add document page dimensions to the onLoadComplete callback

---

android/build.gradle

React Native 0.57 will [scaffold new projects using Gradle 3, instead of Gradle 2](https://github.com/facebook/react-native/commit/6eac2d4e2f5f697043b495002872bfac3e8595cb).
Users who install this library with Gradle 3 will see the following error:
```
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```
This PR fixes this warning.
Please note: this will cause any users who are still on Gradle 2 to see an error:
```
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```
This is because …

Update build.gradle for RN 0.57

---

PdfView.js

In order for VoiceOver users to be able to scroll through the PDF pages, the `PdfPageView` must have an `accessible={true}` tag.

Add support for accessibility

---

ios/RCTPdf/RCTPdfView.m

Disable the magnifying glass and the content section in the pdf-view on iOS to match the same behavior as on Android.

iOS: Disable the longpress-behavior

---

ios/RCTPdf/RCTPdfView.m

To be consistent with behavior on Android, iOS version should cycle through 3 fixed scale factors.

iOS: cycle through min/mid/max scale factors

---

android/build.gradle

Hi,
I managed to fix the issue (that was already opened previously: react-native-pdf:transformNativeLibsWithMergeJniLibsForDebugAndroidTest) 
by adding those lines to the build.gradle file.
after the change build ends successfully.

fix android build issues with react-native-pdf and react-native 59.x

---

ios/RCTPdf/RCTPdfView.m

`removeAnnotation` does not hide the annotation on iOS, `shouldDisplay` does instead

Use shouldDisplay to enable / disable annotation rendering on iOS

---

index.d.ts

The optional `activityIndicatorProps` prop is currently missing from the TypeScript definition.

Add activityIndicatorProps to index.d.ts

---

android/build.gradle

While the work around of adding packagingOptions to the project using react-native-pdf works for the standard debug and release targets, Detox e2e tests build and androidTest target that the work around does not work for, however this change does fix this issue for the Detox build.

Added packagingOptions to android build.gradle

---

android/src/main/java/org/wonday/pdf/PdfView.java

The native dependency [AndroidPdfViewer](https://github.com/barteksc/AndroidPdfViewer/blob/690e2cf3cfa65506cd8a6d176f7c0c0e2beebb8e/android-pdf-viewer/src/main/java/com/github/barteksc/pdfviewer/PDFView.java#L464) is recycling the view in onDetachedFromWindow event. Components like a tabview or the [react-native-viewpager](https://github.com/react-native-community/react-native-viewpager) are not unmounting the component when the native module is detached. We won't have a mount or render callback after returning to the previously loaded pdf page even if the pdf file was unloaded which leads to a blank page.
Steps to reproduce are described in the [example project's](https://github.com/MichaelHettmer/react-native-pdf-fixNativeDetach-example) README.md.
This pull request fixes the described …

Fix blank view after native module got recycled

---

README.md

I was stumbled into why I can't see my PDF file, it's all loaded and no errors. And it's actually because I haven't explicitly set the height, probably other people would stumble upon this so it would be better to add this into the example.

Explicitly set the height on pdf style on example.

---

README.md
index.d.ts
index.js

Currently, rn-fetch-blob is used to fetch a PDF with config option `trusty = true` ([link](https://github.com/joltup/rn-fetch-blob#self-signed-ssl-server)). I have added a prop called "trustAllCerts" to allow the user to set the trusty option.
**Note:** I have set the default value of trustAllCerts as `true` to keep the old behavior. However, it might be better to set the default value as `false` for security reasons.

Expose option "trustAllCerts" to to allow/deny self-signed certificates

---

ios/RCTPdf/RCTPdfView.m

Currently on iOS, setting the background color via the style props doesn't work because the native PDF view is rendereing it's own grey BG color. Setting it to be transparent allows the color from the react style prop to show through.
I will be using this in a production app, and it will have a couple of different background colors in different places, but Please let me know if this would somehow cause issues!
Thanks!

Set the PDF View background color to be transparent so we see the style prop color

---

android/src/main/java/org/wonday/pdf/PdfView.java

Fixed the wrong scale being returned from onScaleChanged() on Android. Previously, the scale returned was the scale difference between onLayerDrawn() calls, rather than overall scale. This PR brings the Android functionality back in-line with it's iOS counterpart, which properly returns the overall scale.

ANDROID: Fixed wrong scale returned from onScaleChanged()

---

package.json

Version 1.0.3 of _react-native-community/progress-bar-android_ & _react-native-community/progress-view_ is required to be able to run on React-Native >= 0.62

Bump dependency to support React-Native >= 0.62

---

react-native-pdf.podspec

This PR fixes a compatibility issue with Xcode 12. React Native libraries should depend on `React-Core` instead of `React`.
For more details take a look at https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

fix: Xcode 12 compatibility

---

index.js

Fixes conditional require of `rn-fetch-blob` on Android and iOS.
Currently, running the sample code fails with the runtime error `undefined is not an object (evaluating 'RNFetchBlob.fs.dirs')`.
This PR fixes this runtime error.

fix: conditional require of rn-fetch-blob

---

windows/RCTPdf/RCTPdfControl.cpp

Fixes a typo in Windows' native code that caused the fitPolicy property to not be applied.

windows: fix typo in fitPolicy property

---

ios/RCTPdf/RCTPdfView.m

This is fixing an issue on iOS versions below 13 where the native PDF View is rendering it's own gray background. It's actually building on this identical issue #233  and this pull request #443 .
However according to [this article](https://medium.com/better-programming/ios-pdfkit-ink-annotations-tutorial-4ba19b474dce) "Calling `pdfView.document = ...` resets PDFView’s background color to default. So, call `pdfView.backgroundColor = ...` after `pdfView.document = ...`."

fix [iOS]: Setting _pdfView.backgroundColor after calling pdfView.document

---

README.md
index.js
windows/RCTPdf/RCTPdfControl.cpp
windows/RCTPdf/RCTPdfControl.h
windows/README.md

Imports `rn-fetch-blob` on Windows as well, with a fallback for functionality that doesn't need `rn-fetch-blob`.
Adds an `if` guard on a possible source of flakiness for the Windows implementation.
Fixes a build error when using with `react-native-windows 0.62`.
Updates the `README.md` for Windows users to consume the `rn-fetch-blob` PR that supports Windows.

windows: import rn-fetch-blob on Windows

---

README.md
index.js
index.js.flow

Gives the ability to add a specific filename when caching the downloaded pdf instead of using `SHA1(uri).pdf`. This way, when trying to share it, the file can have a human-friendly filename.

Add support for setting a filename to the cached pdf file

---

package.json

This PR help to reduce npm package by removing `example` folder.

Reduce NPM package size

---

android/build.gradle
example/android/build.gradle

`jcenter()` deprecated, so it should be replaced by `mavenCentral()`
https://blog.gradle.org/jcenter-shutdown

replace deprecated jcenter()

---

index.js

The download progress is a percentage—a value between 0 and 1. Flooring it will cause it to always be set to 0. Any formatting this value should be the responsibility of the progress rendering function.
This fixes issue #603.

Don't floor progress value when setting progress state

---

index.js

The previous version was rounding to two decimal then rounding to no decimals.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#description

Fix formatting of default progress text to use two fixed decimal places

---

README.md

Added a notice for Expo users about how to setup `react-native-pdf` with custom dev clients. Similar to https://github.com/react-native-webrtc/react-native-webrtc/pull/1114

Added notice about Expo dev client usage

---

ios/RCTPdf/RCTPdfView.m

Re: issue #583 
When loading a PDF with irregular page sizes, using the last page by default to calculate the scale factor can lead to the incorrect scale being applied to the initial page. See above issue for video demo of this.
This PR amends to measure the current page where possible, reverting to the existing behaviour if this is null. 
Resolves #583

Ensure correct scale applied for fit policy on PDFs of irregular page sizes

---

ios/RCTPdf/PdfManager.m

We are unable to preview a PDF on iOS when the file name contains space or special characters: ( "my sample.pdf" or "mySample%20.pdf" ). 
Most widely used [react-native-document-picker](https://github.com/rnmods/react-native-document-picker) to select a file have also added in their [documentation](https://github.com/rnmods/react-native-document-picker#uri) , that users need to decode the file path. 
As discussed in the issue #646   , the decoding is already handled in android by use of `URI.parse` method. Refer Android documentation for the same [here](https://developer.android.com/reference/android/net/Uri#parse(java.lang.String))
The changes include to decode the path in iOS as well. 
Failing to properly decode the path, I am adding fallback to use the provided orignial path string. …

Decode File Path in iOS

---

ios/RCTPdf/RCTPdfView.m

**Why**
getting blank pdf while trying to load pdf which contains space or special characters ( file:///Users/Manan/Library/Developer/C9F05D30-8712-414E-ACBE-BBD37744D6A4/Library/Caches/9978C439-432B-4906-BB9E-4E074842C23A/Manan%20G.pdf)
the file path is getting from react-native-document-picker and we need to decode the file path. it's also mentioned in https://github.com/rnmods/react-native-document-picker#uri
**Issues**
https://github.com/wonday/react-native-pdf/issues/670 https://github.com/wonday/react-native-pdf/issues/646

Fix Show Blank PDF

---

android/src/paper/java/com/facebook/react/viewmanagers/RNPDFPdfViewManagerDelegate.java
android/src/paper/java/com/facebook/react/viewmanagers/RNPDFPdfViewManagerInterface.java

fix typo which causing android build to crash with the following error message
```gradle
> Task :react-native-pdf:compileReleaseJavaWithJavac FAILED
/Users/runner/work/1/s/node_modules/react-native-pdf/android/src/main/java/org/wonday/pdf/PdfManager.java:29: error: PdfManager is not abstract and does not override abstract method showsVerticalScrollIndicator(PdfView,boolean) in RNPDFPdfViewManagerInterface
public class PdfManager extends SimpleViewManager<PdfView> implements RNPDFPdfViewManagerInterface<PdfView> {
^
/Users/runner/work/1/s/node_modules/react-native-pdf/android/src/main/java/org/wonday/pdf/PdfManager.java:97: error: method does not override or implement a method from a supertype
@Override
^
/Users/runner/work/1/s/node_modules/react-native-pdf/android/src/main/java/org/wonday/ …
```

fix typo in RNPDFPdfViewManagerInterface interface causing android build crash

---

ios/RNPDFPdf/RNPDFPdfView.mm

The PR fixed an iOS issue where double-tapping to zoom in on a PDF with a scale greater than 1 caused a fast scrolling and only then zooming to the desired point (video attached). The reason behind is that the custom scrolling conflicts with the _pdfView gesture recognizers
<details>
<summary>Video of the issue</summary>
[Issue Video](https://github.com/wonday/react-native-pdf/assets/138074114/6aa826ff-45f5-44af-93a0-050b78e0dcc0)
</details>
<details>
<summary>Video with the fixes</summary>
[Fixed Video](https://github.com/wonday/react-native-pdf/assets/138074114/867ba1a5-a3bf-46f8-bd39-38c88200eaca)
</details>

fix(iOS): Fix double tap zoom scrolling

---

package.json

Snyk has informed us of a critical vulnerability in the crypto-js package, which is used in the react-native-pdf dependencies. In order to prevent this vulnerability I have updated crypto-js to the latest version. 
For more details you can have a look at this snyk report: 
https://security.snyk.io/vuln/SNYK-JS-CRYPTOJS-6028119
https://github.com/wonday/react-native-pdf/issues/779

fix: bump crypto-js to avoid critical vulnerability

---

index.d.ts

Export the props as well
Because I am creating a component that will show the pdf and I want it to extend the prop of the react-native-pdf but I am unable to access it
Therefore I exported

Exported PDF props (Update index.d.ts)

---

README.md
package.json

Hey, could you please release new version with latest fixes? 🙏 
I've added boilerplate changes for release in this PR

Version bump to 6.7.2

---

index.js

Fixes https://github.com/Expensify/App/issues/29743
This PR is fixing when we add this pdf [class-9-maths-chapter-10-solutions.pdf](https://github.com/Expensify/App/files/12927237/class-9-maths-chapter-10-solutions.pdf) its start crashing on content parse time.
<details>
<summary><b>Video before fixing</b></summary>
https://github.com/wonday/react-native-pdf/assets/16595846/967f2d16-41c5-4258-a2bd-cd42a4b23edb
</details>
<details>
<summary><b>Video after fixing</b></summary>
https://github.com/wonday/react-native-pdf/assets/16595846/849e386e-ce75-4da2-8b79-ab3a88d32916
</details>

fix(Android): crash issue on pdf

---

PdfView.js
README.md
index.d.ts
index.js
index.js.flow

This makes it possible to style the container of the progress indicator (and override the centered style for example).

Add progressContainerStyle to props

---

android/src/main/AndroidManifest.xml

package name missing from androidManifest causes pod install error
https://github.com/wonday/react-native-pdf/issues/787

fix:package name missing pod install error

---

android/src/paper/java/com/facebook/react/viewmanagers/RNPDFPdfViewManagerDelegate.java

Remove @ override in RNPDFPdfViewManagerDelegate.java to fix 'no matching methods to override' error when building android

Remove @override in RNPDFPdfViewManagerDelegate.java to fix 'no matching methods to override' error

---

fabric/RNPDFPdfNativeComponent.js

This PR addresses #831 by adding the missing `enableDoubleTapZoom` to the codegen source file

fix: Add missing 'enableDoubleTapZoom' to fabric codegen source

---

index.js

I have a use case where the user swipes multiple pdf files, and when the pdf is still loading and user swipes it, the cancel function get fired before its initialized. I fixed it by checking if the cancel function exists before calling it.

fix: an issue that crashes when cancel is not present

---

index.js

The decoding of the URI is currently done using `unescape`.
https://github.com/wonday/react-native-pdf/blob/d545ff27b49850c773f6c443dfc65891881c0ed2/index.js#L238
However, this fails if the URI contains an encoded accented name, for example:
ù is encoded to `%C3%B9`, but decoding it using `unescape` gives `Ã¹`.
This PR replaces `unescape` with `decodeURIComponent`.

Fix PDF failed to load when the file URI contains an encoded accented character

---

PdfView.js
ios/RNPDFPdf/RNPDFPdfView.mm

When using enablePaging={true}, horizontal={true}, and showsHorizontalScrollIndicator={false}. 
The scroll indicator is still showing. I attempted to fix this issue.

fix: When using enablePaging={true} and horizontal={true}, showsHorizontalScrollIndicator={false} does not work.

---

android/src/paper/java/com/facebook/react/viewmanagers/RNPDFPdfViewManagerDelegate.java

Following this pr and the following support pr's
- https://github.com/facebook/react-native/pull/46809
- https://github.com/AppAndFlow/react-native-safe-area-context/pull/566/files
- https://github.com/react-native-picker/picker/pull/609/files
- https://github.com/Shopify/flash-list/pull/1484/files
This pr should fix the type issue introduced with react native v0.77

feat: support rn 77

---

package.json

On react-native 0.78 iOS simulator & device pdf was not rendered.

Fix not rendering on iOS - React-native 0.78

---

android/build.gradle

Fixed the crash issue in io.legere:pdfiumandroid that occurred due to multithreading.
Therefore, we need to upgrade the io.legere:pdfiumandroid library to version 1.0.33.

fix: crash issue in io.legere:pdfiumandroid that occurred due to multithreading.
